### ISSUE TITLE
homestead and ralf wait up to 120s before retrying Diameter connection

### ISSUE THREAD

**Issue by mirw** [Metaswitch/cpp-common#106]
I establish a connection from Ralf to my CDF and then restart my CDF.  The TCP connection fails.

```
23-05-2014 11:49:30.737 Debug freeDiameter: Error flag set for socket 320 ({----} TCP,#320->10.151.82.163(3892), ec2-54-198-234-120)
23-05-2014 11:49:30.737 Debug freeDiameter: Sending FDEVP_CNX_ERROR event
23-05-2014 11:49:30.737 Debug freeDiameter: 'STATE_OPEN'        <-- 'FDEVP_CNX_ERROR'   ((nil),0)       '10.151.82.163'
23-05-2014 11:49:30.737 Warning diameterstack.cpp:263: Failed to connect to 10.151.82.163
23-05-2014 11:49:30.737 Error realmmanager.cpp:81: Failed to connect to peer 10.151.82.163
23-05-2014 11:49:30.737 Debug baseresolver.cpp:471: Add 10.151.82.163:3892 transport 6 to blacklist for 30 seconds
23-05-2014 11:49:30.737 Error diameterstack.cpp:276: Unexpected host on callback (type 10) from freeDiameter: 10.151.82.163
23-05-2014 11:49:30.737 Debug freeDiameter: Peer timeout reset to 30 seconds (+/- 2)
23-05-2014 11:49:30.737 Status freeDiameter: 'STATE_OPEN'       -> 'STATE_CLOSED'       '10.151.82.163'
...
23-05-2014 11:49:30.738 Debug freeDiameter: Thread terminated
23-05-2014 11:49:30.738 Debug freeDiameter: '10.151.82.163' in state 'STATE_CLOSED' waiting for next event.
23-05-2014 11:49:30.738 Debug freeDiameter: 'STATE_CLOSED'      <-- 'FDEVP_TERMINATE'   ((nil),0)       '10.151.82.163'
23-05-2014 11:49:30.738 Status freeDiameter: 10.151.82.163: Going to ZOMBIE state (no more activity)
23-05-2014 11:49:30.738 Status freeDiameter: 'STATE_CLOSED'     -> STATE_ZOMBIE (terminated)    '10.151.82.163'
```

(The 2 `Failed to connect...` logs are a bit misleading, BTW.)

We then retry the connection, but this doesn't happen because the peer still exists (apparently as a zombie).

```
23-05-2014 11:49:30.740 Debug realmmanager.cpp:214: Adding peer: 10.151.82.163
23-05-2014 11:49:30.740 Info diameterstack.cpp:574: Peer already exists
23-05-2014 11:49:30.740 Debug realmmanager.cpp:222: Peer already exists: 10.151.82.163
```

About 35s later, freeDiameter garbage collects the zombie peer and the next attempt to add a new peer succeeds.

```
23-05-2014 11:50:05.646 Status freeDiameter: Garbage Collect: delete zombie peer '10.151.82.163'
...
23-05-2014 11:50:05.774 Debug realmmanager.cpp:214: Adding peer: 10.151.82.163
```

**Comment by rkd-msw** [comment]
Hmm. Some notes after hacking away at this for a bit:
* I can't convince myself that not having a STATE_ZOMBIE period before freeing the peer object is safe - there's a potential race condition with message sending, which could pick the peer off the global list and still be using it when the state machine thread frees it. Having a 120-second STATE_ZOMBIE grace period makes it a lot more likely that all pending messages will have been sent before the message is freed.
* There's a second issue - the HOOK_PEER_CONNECT_FAILED hook triggers quite early in processing, before the peer is cleaned up or removed (and it's triggered from several places). This hook triggers a condition variable (in RealmManager::connection_failed) which makes `manage_connections` run immediately, but there's a good chance that will run and try to add a new peer before the freeDiameter thread has advanced far enough to remove it. So the first attempt to add a peer is pretty likely to fail because of that ordering issue, and you'll have to wait for your DNS TTL before it tries again, at which point you might as well have just waited the 120s for freeDiameter's GC thread to run (and it runs every 120s, so you'll only wait for an average of 60s).
* Relatedly, it's really hard to reason about what state things are in after HOOK_PEER_CONNECT_FAILED - it gets called in a lot of different situations and isn't very well-documented.
* I can't repro this when using hss_hostname on Homestead, only when using hss_realm - which agrees with my suspicion that this is related to how RealmManager handles connections and how it gets triggered by freeDiameter.

I'm starting to suspect that this will be quite big to fix properly, and involve a bit of rearchitecting in freeDiameter to make it better fit this use-case of a RealmManager sitting on top recycling connections frequently. (Specifically, making the hooks more useful, and maybe adding reference-counting or something so that peers can be deleted safely without a long STATE_ZOMBIE period.)

**Comment by rkd-msw** [comment]
Actually, maybe this whole question is pretty artificial - if a Diameter peer goes down, it's reasonably unlikely that we'll be able to reconnect to it as soon as we spot the failure and trigger HOOK_PEER_CONNECT_FAILED. So we'll usually have to wait for our DNS TTL anyway, which is not likely to be a lot shorter than the ~60s you'll need to wait on average for the peer to be garbage-collected from STATE_ZOMBIE.

(Plus, in production, you'd have redundant peers - so if you hit this, you'd just use a backup peer for a few minutes.)

**Comment by mirw** [comment]
I'm not sure I buy this last point - we have no idea why the Diameter peer might have gone down!

One common scenario is that the peer has crashed.  How long does it take for the peer to restart?  Well we know that OpenIMSCore HSS isn't particularly quick but there's no reason that non-Java-based implementations would be that slow.  I bet if we wrote an HSS using the freeDiameter stack, it would only take a second or two to come back up after failure.

Another scenario is that network connectivity to the peer has previously been down.  In that interval, any transmission from the peer would have failed and brought the connection down.  If the only transmission we have to the peer is the DWR/DWA poll, it would be possible for the peer to have failed the connection in the meantime, so when we send the DWR, we immediately receive a TCP RST/ACK.  However, the peer is alive, so retrying immediately would work.

The problem with relying on redundant peers is that you don't know what caused this event.  If you have 2 peers (and connections to both) and the brief network outage affects all peers (quite plausible), then waiting 2 minutes for it to recover means 2 minutes of no service.

**Comment by graemerobertson** [comment]
Also, the Diameter peer doesn't have to go down to get into this state. Consider Ralf connected to CDFs A and B. We do a DNS lookup and get peers A and C back - B is still fine, but DNS has returned A and C this time. We establish connections to A and C and drop the connection to B. C now dies (for whatever reason) and so we immediately want to connect to B again. But freeDiameter doesn't try to connect because B is in this zombie peer state.

**Comment by bossmc** [comment]
As we focus on Rf resiliency, I'm raising the priority of this to get it looked at.

**Comment by eleanor-merry** [comment]
Reducing priority as we won't work on this until there's a story

**Comment by graemerobertson** [comment]
*Copied from my email*

The root of the problem here is not that the zombie peer is left lying around, but rather that we can’t add a peer if it already exists as a zombie – there is no good reason for that to be the case. Initially I thought that if we discovered the peer already existed as a zombie in `fd_peer_add` then we should just move it out of zombie state again (which is exactly what we do when we receive a new CER from zombie peer). However, I’m nervous about how much of the existing peer structure would be accurate – it feels like we’d want to effectively completely re-write the peer object, and this might not be safe because the individual peers don’t have locks.

Instead, my solution is that we just go ahead and add the peer anyway. This would mean that the global peers list can contain multiple peers with the same Diameter identity, but all but one of them must be in zombie state (and in fact all of them could be in zombie state).

**Does this solution work?**

It seems to! It fixes the problem, but I'm running through some more tests to check I haven't broken anything else.

**Why is this solution safe?**

I’ve checked all of the places the `fd_g_peers` list is used, and I think we’re good.
* We walk the list in `gc_th_fct` in `p_expiry.c` in order to delete all peers in zombie state. This is good, we want to continue to do this.
* Otherwise the list only gets used in `peers.c.`
  * We initialise the list.
  * We walk over the list in `fd_peer_add`, but we know this already.
  * We walk over the list in `fd_peer_remove`; we should change this function so that we keep walking over the list if we find a zombie version of our peer.
  * We walk over the list in `fd_peer_getbyid`; this is fine but we need to think about what this function should now return by seeing how it’s used.
    * Declared in `libfdcore.h` – we should update the function comment to reflect its new exact behaviour.
    * The function gets used in `routing_dispatch.c`.
    * Used in `don’t_send_if_no_common_app`, a function used to “prevent sending to peers that do not support the message application” – we can’t send to a zombie anyway, so as long as `fd_peer_getbyid` returns the non-zombie by preference, this is fine (and will match current behaviour).
    * Used in `return_error`, a function used to “return an error to an incoming request” – we can’t send to a zombie anyway, so as long as `fd_peer_getbyid` returns the non-zombie by preference, this is fine (and will match current behaviour).
   * Used in msg_rt_out twice – but the same story here.
  In conclusion, I think it should actually be safe for fd_peer_getbyid to never return zombies, but just to be extra safe I think we should return a non-zombie if we can, and otherwise the first zombie we find.
  * We walk over the list in `fd_peer_fini_force` to terminate all peers. This is fine.
  * We walk over the list in `DECLARE_FD_DUMP_PROTOTYPE`. This is fine.
  * We walk over the list `fd_peer_handle_newCER`. Currently (as described above) we re-activate zombies here, but for sanity I think we should change this in order to replicate my new behaviour (especially as we’d now have to walk over the whole list to check that there aren’t any active peers before re-activating a zombie).

I can’t think of anything else that would make this unsafe; we’re only tweaking the set of elements in fd_g_peers, and I’ve enumerated all of the places this list is used.

**Comment by bossmc** [comment]
What a time to be alive!

**Comment by graemerobertson** [comment]
Fixed by https://github.com/Metaswitch/freeDiameter/pull/34
