### ISSUE TITLE
Memcached TCP connections still try to be used after they've closed

### ISSUE THREAD

**Issue by mirw** [Metaswitch/cpp-common#286]
While investigating https://github.com/Metaswitch/sprout/issues/1010, I observed that Sprout's connections to memcached can be closed by the memcached daemon without Sprout acting on this.  Instead, next time Sprout needs to use memcached (which could be minutes or even hours later), it may try to use one of these connections, fail and fall back to the backup.

This is bad because

*   Sprout ends up using the backup Memcached instance rather than the primary more frequently than it should (which impacts fault-tolerance)
*   Sprout takes longer to retry these connections than it should (which marginally impacts performance)
*   Sprout takes longer to spot failures than it should (which impacts monitoring).

Fixing the first bullet alone might be a priority, and could be achieved by always doing a non-blocking read before writing to the TCP connection - the non-blocking read would return that the connection has been closed.

**Comment by graemerobertson** [comment]
There are two test cases in test_memcachedsolution.cpp in the clearwater-fv-test repo that have TODOs that are blocked by this issue. See the test cases for more detail, but essentially they have an extra branch to handle data contentions that wouldn't happen if it weren't for this issue. Those branches should be deleted once this issue is resolved.

Note that test_memcachedsolution.cpp only exists in the sto1614 branch in clearwater-fv-test at time of writing. The plan is to merge this branch into master at some point in the not too distant future, but that is not related to this issue.

**Comment by graemerobertson** [comment]
@AlexHockey I think you're looking at this this sprint so I'm aggressively assigning to you

**Comment by AlexHockey** [comment]
I've done some digging into libmemcached's connection management logic. It is simpler and less sophisticated than we thought. When libmemcached needs to contact a server:

*  If it has a file descriptor to that server, it will try to use the fd. If there is a failure it does not attempt to re-establish the connection - it just clears closes the fd. 
*  If it does not have a fd it will check whether the server is on a "timeout" (a terrible name - this acts like a blacklist). 
  * If it is not on a timeout, libmemcached tries to connect, blocking the calling thread until this completes (successfully or unsuccessfully). 
  * If it is on a timeout, libmemcached fails the request immediately. A server is put on a timeout if a connection attempt fails, and stays in that state for 2 seconds. 

We had previously thought that if libmemcached tried to use an existing connection but found out it was down, that it would try to reconnect asynchronously (which would have meant the next request probably wouldn't have had to wait for the connection to come up). This understanding is wrong, and the next request will *always* block.

**Comment by AlexHockey** [comment]
So whenever a connection breaks under its feet, libmemcached is going to force at least one request to block while it tries to reconnect. This might as well be the request that spotted the broken connection. So all we need is a way to spot that the connection has gone down.

**Comment by AlexHockey** [comment]
Right, so I've got three possible solutions in mind:

1. As @mirw mentions above, if libmemcached already has a fd, do a non-blocking `recv` on that fd before using it. If this returns 0 carry on as if it didn't have a fd. This catches the case where the server closes the connection gracefully, which I think covers situations like the memcached process crashing or being terminated, and graceful reboots of the VM - but not things like power failures or other unexpected reboots. 

2. Have the client code retry to the same server whenever it gets a connection error. The idea is that if the connection was previously up, the request will fail and the client will try to re-connect immediately. If the connection was not previously up, the client will try to connect at most once (the second connect being stopped by the blacklisting behavior). This catches all memcached failure modes. 

3. Poll active connections in the background (using memcached no-op commands). This is slightly tricky for Astaire as the connections are stored in thread-local data. These would need to be moved out into a shared pool (like the clients will shortly be using) which means a bit of refactoring of Astaire's `MemcachedBackend`.

I'm currently leaning towards option 2 as it is the smallest change that catches all failure modes.

**Comment by mirw** [comment]
What's the impact of option 2 on network latency when a node is permanently failed (and unresponsive).  Do we have a 50ms connection timeout on every request?

**Comment by AlexHockey** [comment]
Yes, but we get that latency today (i.e. even if we don't make any fix). The only option that would cut down on that latency is 3).

**Comment by AlexHockey** [comment]
Option 2 won't "just work" because for some reason when libmemcached sends a binary request, if the send fails for any reason at the transport level (failure to connect, connection closed, etc), it "resets" the connection which has the effect of disabling the in-built blacklisting. It also returns `MEMCACHED_WRITE_FAILURE` which means that even if blacklisting was working, there would be no way for the client to tell (so I guess that's consistent, if not intended). 

I think we should probably do option 1) for now (as it is simple and improves our behavior in some failure modes) and work out if we want to keep using libmemcached before making any other fixes (it seems like it's just getting in the way more than it helps recently).

**Comment by AlexHockey** [comment]
I'm closing this issue as we've got as good behavior as we can without using a different memcache client.
