### ISSUE TITLE
Memcached not replicating data in a GR system

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/cpp-common#609]
#### Symptoms
On a GR system with 50ms latency between the two sites (i.e a 100ms round-trip time) I noticed that registrations weren't being replicated across to the remote site - the initial get from the remote site always failed with `error 47 (SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY)`. 

#### Impact
Any call between subscribers that had registered in different sites failed. No protection against site failure.

#### Release and environment 
From at least Vulpix

**Comment by eleanor-merry** [comment]
The issue is that we had a hard coded limit of 50ms on any memcached connection - the fix is to increase this value. We've gone for a large value here so that we won't realistically hit timeouts (and we rely on the existing timeout code to handle retries, blacklisting, etc..)

**Comment by eleanor-merry** [comment]
@rkd-msw can I pass this to you to see if you hit this again when you do more testing of GR?

**Comment by rkd-msw** [comment]
Yep, will do.

**Comment by rkd-msw** [comment]
@eleanor-merry - are there any other fixes needed to make GR work, or do you expect everything will now be fine tomorrow?

**Comment by eleanor-merry** [comment]
Somewhere in between - I don't know of any other fixes that need to go in now.

**Comment by rkd-msw** [comment]
It's currently working - calls are getting through with 100ms latency (200ms round-trip time) but I saw some memcached timeouts when I started testing (with either 50ms or 100ms latency - unfortnately I don't know which).

Specifically, I've seen calls fail with 480 errors, with the SAS logs "Sending get request to memcached for key reg\\sip:50232007@gr-stress.clearwater.test" (at 12:08:32.159) and "Memcached get request failed for key reg\\sip:50232007@gr-stress.clearwater.test

Error: A TIMEOUT OCCURRED" (at 12:08:32.360).

I don't understand why these requests are timing out - but that's partly because the SAS logs don't contain memcached IP addresses so I can't tell where it's reading from. I guess that we haven't found the data locally so we're hitting https://github.com/Metaswitch/sprout/blob/ee05b98c9f533fc8f34c19d2ccb122f5533bed51/src/scscfsproutlet.cpp#L234 and reading cross-site - but that shouldn't time out and the data should have been replicated to this site....

I've attached:

* SAS trace of a failed call
* SAS trace of the registration corresponding to the user we failed to find on the failed call
* a diags package from the system that handled the REGISTER (in site1)
* a diags package from the system that handled the call (in site2)

**Comment by eleanor-merry** [comment]
This should be improved by https://github.com/Metaswitch/cpp-common/pull/614; passing back for retest

**Comment by rkd-msw** [comment]
Not improved, but that's because https://github.com/Metaswitch/sprout/commit/247cd66337cd7149021f0a5ada40792f26d883e0 passes `true` as the remote_store argument on the local store and `false` as the remote_store argument on the remote store, so we have a 250ms local timeout and a 50ms remote timeout.

**Comment by rkd-msw** [comment]
(https://github.com/Metaswitch/ralf/pull/263/files has the same issue)

**Comment by eleanor-merry** [comment]
Nailed it :). 
It's now the correct way round so passing back.

**Comment by rkd-msw** [comment]
Yep - I'm now seeing 100% call success on GR stress even with 100ms latency. (I'm effectively seeing 100% REGISTER success too - the only failures are because I'm powering off the Sprout node handling REGISTERs partway through.)

http://abra:8080/view/Stress/job/stress-gr/73/ has that stress run.
